### ISSUE TITLE
KDA Timings for League of Legends

### ISSUE THREAD

**Issue by Yingah** [lulzsun/RePlaysTV#17]
Not sure how feasible it is to incorprate now but a nice funtion to have back is the KDA timestamps for League Of Legends -Along with filter by kills/deaths/assists too. Continue the good work

**Comment by lulzsun** [comment]
I'm in the process of completing the re-implementation of this feature. Look out for it in the next update.

**Comment by taylornguyen** [comment]
any major roadblocks? you should be able to pull this from riot api right?

**Comment by lulzsun** [comment]
Yes, using the League Client API.

This has been reimplemented but has not been released. I forgot to tag the commit with the changes to this issue. I will close this issue now.
