### ISSUE TITLE
Error with LTC DLL

### ISSUE THREAD

**Issue by jJ428ac6M2HS** [lulzsun/RePlaysTV#21]
Hello,

Since I installed RePlaysTV, I have a popup showing up every ~15 minutes if the PC is active. 
The popup is called "LocalBridge.exe - Image incorrecte" which apparently translate to "incorrect parameter".

Then it says "C:\Users\Name\AppData\Local\Plays-ltc\0.54.7\ltc_help64-47766-7e77e412.dll is not conceived to run on windows or contains an error."

Wonder if you have any idea where that might come from.

**Comment by lulzsun** [comment]
Hello,

This issue has existed ever since, before Replays existed. I don't think this is fixable until a new method of recording is implemented. Reformatting is an option but is extreme.

Closing this because it will not be fixed.
