### ISSUE TITLE
Overwatch bookmark

### ISSUE THREAD

**Issue by AdekexXxx** [lulzsun/RePlaysTV#24]
While I play Overwatch it doesnt bookmarked Kills
nice when you fix this, would be that it also bookmarked at assists :) 

sorry for my bad english

**Comment by lulzsun** [comment]
Hi, unless you provide any game integration API docs of either game, it will be very hard to implement. Quick google search leads me to no results, so I am assuming both of these games do not provide any game integration APIs that will allow us to hook events (kills, assists, deaths) in game.

Closing this issue for now.
