### ISSUE TITLE
Getting stuck on splash screen

### ISSUE THREAD

**Issue by rafaelvanderlei** [lulzsun/RePlaysTV#26]
Hi, I've jsut installed for the first time both plays.tv and RePlaysTV.

When I try to open the software, I get stuck on splash screen, like below:

![replaystv_stuck_on splash](https://user-images.githubusercontent.com/759178/78741230-37835880-792f-11ea-9e98-f02fc75f9a47.png)

Has it happened to anyone else? Does anyone know how to solve it?

Thanks.

**Comment by lulzsun** [comment]
Have you tried version 3.0.3a?

**Comment by rafaelvanderlei** [comment]
I'm actually using 3.0.3 (not 3.0.3a). Shouldn't that version work though?

**Comment by lulzsun** [comment]
3.0.3a is meant to fix this issue.

**Comment by rafaelvanderlei** [comment]
ahh, ok... I'm gonna try that out and let you know the outcome. Thanks!

**Comment by rafaelvanderlei** [comment]
Hey, confirmed. Installing 3.0.3a fixed the problem. 

Somehow I missed the bolded message notifying to make sure to install 3.0.3a and ended up choosing to download 3.0.3, sorry about that.

Thanks and congrats for the great work.

**Comment by lulzsun** [comment]
No problem!
