### ISSUE TITLE
Two Error Messages

### ISSUE THREAD

**Issue by tetreaultc** [lulzsun/RePlaysTV#27]
RePlays seems to work fine as it records my games without any problem.  However, when the application is running, I constantly get those 2 error messages:

- LocalBridge.exe - Bad Image
- AppleMobileDeviceProcess.exe - Bad Image

![RePlays-Errors](https://user-images.githubusercontent.com/46608523/78920200-073bd700-7a61-11ea-9abd-0b54477078ea.jpg)

**Comment by lulzsun** [comment]
This is currently a Windows 10 issue and is not related to Plays. [This project also features the same issue](https://github.com/digitalcreations/MaxTo/issues/415) so maybe you can try the few workarounds in that issue and see if it helps.
