### ISSUE TITLE
CS:GO Recording Issue

### ISSUE THREAD

**Issue by xanaxw** [lulzsun/RePlaysTV#28]
Hey, I got this, I don't wanna say issue, but it kinda is, you see, I play HvH which means "Hacker vs Hacker", the problem I'm facing is that the "ESP" hack doesn't fully show, the name, health bar and gun.
I had this "problem" with the original Plays app before. Still, I didn't bother and used NVidia GeForce now, which I don't like anymore.

It's supposed to look like this on the recording: http://prntscr.com/rwqttq
But instead, it looks like this: http://prntscr.com/rwqy2n

**Comment by lulzsun** [comment]
From my understanding, hacks that are drawing the overlay either outside of the game process, using opengl, or something similar usually doesn't get picked up by most recording software (like OBS). They normally call these "streamer-safe" hacks.

I don't think I will be fixing this.
