### ISSUE TITLE
RePlaysTV doesn't record my microphone, but records everyone else's on discord

### ISSUE THREAD

**Issue by bogeye1212** [lulzsun/RePlaysTV#30]
My replays work great but my own voice doesn't appear.

**Comment by RMEngelbrecht** [comment]
Make sure you actually have your own microphone enabled in the RePlays client. Check this in `Settings > Audio > Microphone Settings`.
Your own microphone isn't part of the desktop audio like your friends in discord voice chat. 
I'd advice you to set the microphone settings to "open microphone"

**Comment by lulzsun** [comment]
I am closing this since this sounds like it is unrelated to RePlays and more of a user error type situation.
