### ISSUE TITLE
Black screen on recorded videos in League of legends

### ISSUE THREAD

**Issue by geoffho** [lulzsun/RePlaysTV#34]
I am experiencing a black screen with audio on my recorded League of legends replays.
I am unable to rollback my windows10 updates because it has been over 10days since the update. What would solve this issue?

**Comment by UdonBdon** [comment]
Same, I recently reinstalled replays and now i'm getting a black screen for just league of legends.

**Comment by lulzsun** [comment]
There is no fix if you can't rollback the update. You will have to wait until major changes and development to RePlays.

Closing this as it is a duplicate of #20
