### ISSUE TITLE
FPS Issue

### ISSUE THREAD

**Issue by Salients** [lulzsun/RePlaysTV#36]
Massive FPS issues in League of Legends. I have no idea why my FPS is so terrible. A friend of mine has ReplaysTV and his FPS is fine. I need steps on what to do to fix this. I used PlaysTV before and my FPS was fine. Idk what happened :(

**Comment by lulzsun** [comment]
This sounds like a specific case with your system. Without enough information, I can't provide much help or knowledge as to what is causing it.

Closing this issue because it is lacking detail. You can reopen this issue if you can provide more detail or figure out the root of the issue.
