### ISSUE TITLE
RePlaysTV prevents Riot Games' Valorant to not start

### ISSUE THREAD

**Issue by un0btanium** [lulzsun/RePlaysTV#37]
I makes an error noise and nothing more. Every now and then I get an memory access error. The game does not even start. As soon as I close RePlaysTV the game starts just fine.

**Comment by lulzsun** [comment]
I have personally tested Valorant with RePlays and have not run into this issue.

Without any further information, I don't think I can provide any help or knowledge as to why this is happening.
