### ISSUE TITLE
Replace the Web.archive.org link with this

### ISSUE THREAD

**Issue by JayBoom** [lulzsun/RePlaysTV#40]
I get a lot of comments on my tutorial video and on the reddit about the web archive link not working, and apart from that I did a test, web archive locks it at a max of 1.2mb/s download speed when downloading (I regularly only got like 300kb/s while downloading from that mirror) but when I uploaded the setup from the same link to dropbox, and downloaded it again, it downloaded at 12mb/s (my DL speed)

So yeah, I think you should replace that link with this https://www.dropbox.com/s/11b5fptw2qsjmn5/PlaysSetup.exe?dl=0

So instead of the "Here" being a link to Webarchive.org it should be [Here](https://www.dropbox.com/s/11b5fptw2qsjmn5/PlaysSetup.exe?dl=0)

**Comment by lulzsun** [comment]
Done.
