### ISSUE TITLE
ltc_help64_47766-7e77e412.dll error

### ISSUE THREAD

**Issue by jekyllgrim** [lulzsun/RePlaysTV#43]
After my latest Windows update this LocalBridge.exe error keeps popping up referring to a supposedly Plays.Tv file.
![image](https://user-images.githubusercontent.com/42670463/82047697-f0ba1880-96bb-11ea-9e64-83adb2aebdde.png)

I tried reinstalling plays.tv and replays.tv but it didn't help. The program is running but not recording anything when this error appears. It throws several error messages at once, layered one atop the other.

**Comment by iLynxx** [comment]
i have the exact same problem, really annoying

**Comment by lulzsun** [comment]
Possible solution in this [duplicate issue](https://github.com/lulzsun/RePlaysTV/issues/59#issuecomment-650681121). Closing this.
